version: '3'
services:
  translations-db:
    build: db
    container_name: translations-db
    env_file:
      - .env
    ports:
      - "5425:5432"
    volumes:
      - translations-db-data:/var/lib/postgresql/data

volumes:
  translations-db-data: